# Generated by Django 3.1.2 on 2020-10-01 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhostPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_boast', models.BooleanField(default=True)),
                ('post', models.CharField(max_length=280)),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('time_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('sec_key', models.CharField(max_length=6)),
            ],
        ),
    ]
