# Generated by Django 3.1.2 on 2020-10-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='post',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
