# Generated by Django 3.1.2 on 2020-10-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201002_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='is_boast',
            field=models.CharField(choices=[('B', 'BOAST'), ('R', 'ROAST')], max_length=1),
        ),
    ]
