# Generated by Django 3.1.2 on 2020-10-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201002_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='is_boast',
            field=models.CharField(choices=[('Boast', 'Boast'), ('Roast', 'Roast')], max_length=5),
        ),
    ]
